apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: battle-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MathanbabuMoorthi/argocd.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: battle
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
